version: "3.4"
services:
  webapp:
    image: django-accounts
    volumes:
      - ${PWD}/db.sqlite3/:/app/db.sqlite3
      - ${PWD}/media/:/app/media/
      - ${PWD}/logs/:/app/logs/
      - ${PWD}/staticfiles/:/app/staticfiles/
      - ${PWD}/src/gameplay/:/app/gameplay/
      #- ${PWD}/src/main/settings.py:/app/main/settings.py
      #command: python3 manage.py runserver 0.0.0.0:8000
    secrets:
      - source: dotenv
        target: /app/main/.env
    depends_on:
      - redis
    #ports:
    #  - "8000:8000"

  nginx:
    image: nginx
    volumes:
      - ${PWD}/nginx/:/etc/nginx/conf.d/
    #  - /etc/letsencrypt:/etc/letsencrypt
    #  - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
    #  - "443:443"
    depends_on:
      - webapp
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

secrets:
  dotenv:
    file: .env
    
