# Generated by Django 3.0.8 on 2020-08-11 22:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='upload',
            field=models.FileField(upload_to=accounts.models.upload_path),
        ),
    ]
