# Generated by Django 3.0.8 on 2020-08-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='receipients',
        ),
    ]
