# Generated by Django 3.0.8 on 2020-08-15 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_remove_notification_receipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(blank=True, null=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
